
<div class="nested-container">

    <div class="page-banners grid-container row-prod-spec">
        <?php
        $category_special_prod = 128; //categoria special products
        $count = 2;
        $count2 = 0;

        $products_spec = Mage::getModel('catalog/category')->load($category_special_prod);
        $productsspeciallist = $products_spec->getProductCollection()->addAttributeToSelect('*')->addAttributeToSelect('price');
        ?>

        <?php foreach($productsspeciallist as $product): ?>

            <div class="grid12-3 mobile-grid banner prod-spec-first-div" style="height: 250px;">

                <div class="prod-spec-container-div">
                    <h5 class="prod-spe-price"><?php echo number_format($product->getPrice(), 2, '.', '').'€';?></h5>
                    <h3 class="prod-spe-finalPrice"><?php echo number_format($product->getFinalPrice(), 2, '.', '').'€'; ?></h3>
                    <span class="prod-spe-name">Short Claro</span>
                        <a href="<?php echo $product->getProductUrl(); ?>"><span class="prod-spe-plus">+</span></a>
                </div>

                <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')/*->resize(275, 300)*/; ?>" alt="<?php echo $product->getName()?>" />

            </div>

            <?php if ($count <= 0): break; ?>
            <?php endif; ?>
            <?php $count--; ?>

        <?php endforeach; ?>
        <div class="grid12-3 mobile-grid banner prod-spec-first-div">
            <div class="clp-shorts-div">
                <h3>CLP<br>SHORTS</h3>
                <p>Descubre todos nuestros nuevos modelos de shorts para verano</p>
                <div class="view-more">
                    <a href="<?php echo $products_spec->getUrl(); ?>" class="go">VER MÁS</a>
                </div>
            </div>
        </div>
    </div>

    <div class="page-banners grid-container row-prod-spec">
        <?php foreach($productsspeciallist as $product): ?>

            <?php if ($count2 > 2): ?>
                <div class="grid12-3 mobile-grid banner prod-spec-first-div">

                    <div class="prod-spec-container-div">
                        <h5 class="prod-spe-price"><?php echo number_format($product->getPrice(), 2, '.', '').'€';?></h5>
                        <h3 class="prod-spe-finalPrice"><?php echo number_format($product->getFinalPrice(), 2, '.', '').'€'; ?></h3>
                        <span class="prod-spe-name">Short Claro</span>
                        <a href="<?php echo $product->getProductUrl(); ?>"><span class="prod-spe-plus">+</span></a>
                    </div>

                    <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image'); ?>" alt="<?php echo $product->getName()?>" />

                </div>
            <?php endif; ?>
            <?php $count2++; ?>

        <?php endforeach; ?>
    </div>

    <!--<div class="page-banners grid-container">
        <div class="grid12-3 mobile-grid banner">
            <img style="position:absolute;margin-left:180px;margin-top:20px;" src="<?php echo $this->getSkinUrl('images/home/sp_prod/pr1.png') ?>" alt="T-shirt" />
            <img src="<?php echo $this->getSkinUrl('images/home/sp_prod/sp4.png') ?>" alt="T-shirt" />
        </div>
        <div class="grid12-3 mobile-grid banner">
            <img style="position:absolute;margin-left:180px;margin-top:20px;" src="<?php echo $this->getSkinUrl('images/home/sp_prod/pr1.png') ?>" alt="T-shirt" />
            <img src="<?php echo $this->getSkinUrl('images/home/sp_prod/sp5.png') ?>" alt="T-shirt" />
        </div>
        <div class="grid12-3 mobile-grid banner">
            <img style="position:absolute;margin-left:180px;margin-top:20px;" src="<?php echo $this->getSkinUrl('images/home/sp_prod/pr1.png') ?>" alt="T-shirt" />
            <img src="<?php echo $this->getSkinUrl('images/home/sp_prod/sp6.png') ?>" alt="T-shirt" />
        </div>
        <div class="grid12-3 mobile-grid banner">
            <img style="position:absolute;margin-left:180px;margin-top:20px;" src="<?php echo $this->getSkinUrl('images/home/sp_prod/pr1.png') ?>" alt="T-shirt" />
            <img src="<?php echo $this->getSkinUrl('images/home/sp_prod/sp7.png') ?>" alt="T-shirt" />
        </div>
    </div>-->

</div>
