<br/>
<br/>
<div class="nested-container">

    <div class="page-banners grid-container">
        <div class="grid12-4 mobile-grid banner ultimo-div">
            <img class="ultimo-img" src="<?php echo $this->getSkinUrl('images/home/ultimo/ult1.png') ?>" alt="T-shirt" />
            <h3>ME ENCANTA EL SERVICIO DE CLP. SERVICIO RAPIDO Y DE FIAR</h3>
            <p>Aenean at tellus tempor, placerat ante quis, volutpat justo. Donec mattis quam id auctor malesuada. Donec consequat vitae nunc nec eleifend.</p>
        </div>
        <div class="grid12-4 mobile-grid banner ultimo-div">
            <img class="ultimo-img" src="<?php echo $this->getSkinUrl('images/home/ultimo/ult2.png') ?>" alt="T-shirt" />
            <h3>FUE ENTRAR EN LA WEB Y ENAMORARME DE SU SENCILLEZ PARA COMPRAR</h3>
            <p>Aenean at tellus tempor, placerat ante quis, volutpat justo. Donec mattis quam id auctor malesuada. Donec consequat vitae nunc nec eleifend.</p>
        </div>
        <div class="grid12-4 mobile-grid banner ultimo-div">
            <img class="ultimo-img" src="<?php echo $this->getSkinUrl('images/home/ultimo/ult3.png') ?>" alt="T-shirt" />
            <h3>PUEDO COMPRAR COMO QUIERA. LAS OPCIONES SON VARIADAS</h3>
            <p>Aenean at tellus tempor, placerat ante quis, volutpat justo. Donec mattis quam id auctor malesuada. Donec consequat vitae nunc nec eleifend.</p>
        </div>
    </div>

</div>
<br/>
<br/>
<br/>
<br/>