<br/>
<br/>
<div class="nested-container">

    <div class="page-banners grid-container">
        <div class="grid12-2 mobile-grid banner penultimate-div">
            <img class="penultimate-img" src="<?php echo $this->getSkinUrl('images/home/penultimate/pen1.png') ?>" alt="T-shirt" />
            <h3>STOCK SIEMPRE DISPONIBLE</h3>
            <p>En nuestra tienda online podrás gestionar tus pedidos y acceder a tu panel de cliente y gestionar tu cuenta.</p>
        </div>
        <div class="grid12-2 mobile-grid banner penultimate-div">
            <img class="penultimate-img" src="<?php echo $this->getSkinUrl('images/home/penultimate/pen2.png') ?>" alt="T-shirt" />
            <h3>SIN PACK NI LOTES</h3>
            <p>Ppuedes comprar prendas sueltas si así lo deseas y añadir al carrito para comprar.</p>
        </div>
        <div class="grid12-2 mobile-grid banner penultimate-div">
            <img class="penultimate-img" src="<?php echo $this->getSkinUrl('images/home/penultimate/pen3.png') ?>" alt="T-shirt" />
            <h3>BAJO GASTOS DE ENVÍO</h3>
            <p>Gastos de envío por sólo 5 euros y si haces un pedido grande (mil euros) el gasto de envío es gratuito.</p>
        </div>
        <div class="grid12-2 mobile-grid banner penultimate-div">
            <img class="penultimate-img" src="<?php echo $this->getSkinUrl('images/home/penultimate/pen4.png') ?>" alt="T-shirt" />
            <h3>DISEÑADO EN ESPAÑA</h3>
            <p>Nuestro almacén y central se encuentra ubicado en Utrera (Sevilla).</p>
        </div>
        <div class="grid12-2 mobile-grid banner penultimate-div">
            <img class="penultimate-img" src="<?php echo $this->getSkinUrl('images/home/penultimate/pen5.png') ?>" alt="T-shirt" />
            <h3>ATENCIÓN AL CLIENTE</h3>
            <p>Disponemos de un excelente servicio de atención al cliente y te atendemos por correo o teléfono.</p>
        </div>
        <div class="grid12-2 mobile-grid banner penultimate-div">
            <img class="penultimate-img" src="<?php echo $this->getSkinUrl('images/home/penultimate/pen6.png') ?>" alt="T-shirt" />
            <h3>EXCLUSIVIDAD PARA TI</h3>
            <p>Nuestra colección dispone también de exclusividad geográfica para aquellos que lo soliciten.</p>
        </div>
    </div>

</div>
<br/>
<br/>
<br/>
<br/>