
            <h2 class="title-wom-men">NOVEDADES HOMBRE / MUJER</h2>

            <?php
                $category_women_id = 126; //categoria women

                $products_women = Mage::getModel('catalog/category')->load($category_women_id);
                $productswomenlist = $products_women->getProductCollection()->addAttributeToSelect('*');
            ?>

            <?php foreach($productswomenlist as $product): ?>

                    <div class="grid12-3">

                        <!--<div class="feature feature-icon-hover indent indent-size-xl">-->
                            <a href="<?php echo $product->getProductUrl() ?>">
                                <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->resize(255, 373); ?>" alt="<?php echo $product->getName()?>" />
                            </a>
                        <!--</div>-->
                    </div>

            <?php endforeach; ?>

            <div class="grid12-3">

                <div class="women-offer">
                    <p class="wom-text">Novedades Mujer</p>
                    <div class="wom-view_more">
                        <a href="<?php echo $products_women->getUrl(); ?>" class="go">VER MÁS</a>
                    </div>
                </div>

            </div>

            <div class="clearer"></div>
            <br/>
            <br/>

            <?php
                $category_men_id = 127; //categoria men

                $products_men = Mage::getModel('catalog/category')->load($category_men_id);
                $productsmenlist = $products_men->getProductCollection()->addAttributeToSelect('*');
            ?>

            <div class="grid12-3">

                    <div class="men-offer">
                        <p class="wom-text">NOVEDADES HOMBRE</p>
                        <div class="wom-view_more">
                            <a href="<?php echo $products_men->getUrl(); ?>" class="go">VER MÁS</a>
                        </div>
                    </div>

            </div>

            <?php foreach($productsmenlist as $product): ?>

                <div class="grid12-3">

                    <!--<div class="feature feature-icon-hover indent indent-size-xl">-->
                        <a href="<?php echo $product->getProductUrl() ?>">
                            <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->resize(255, 373); ?>" alt="<?php echo $product->getName()?>" />
                        </a>
                    <!--</div>-->
                </div>

            <?php endforeach; ?>

            <div class="clearer"></div>
            <br/>
            <br/>
            <br/>
            <br/>



