<!-- ESTO ES LO QUE HABÍA ANTES EN CMS PAGES EN CONTENT
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="ic ic-2x ic-paint ib ib-size-xxxl"></span>
        <h6 class="above-heading">Customizable design</h6>
        <h3>Unlimited Colors</h3>
        <p>You have never seen so many options! Change colors of dozens of elements, apply textures, upload background images...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div>
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="ic ic-2x ic-smartphones ib ib-size-xxxl"></span>
        <h6 class="above-heading">12-column grid</h6>
        <h3>Responsive Layout</h3>
        <p>Ultimo can be displayed on any screen. It is based on fluid grid system. If screen is resized, layout will be automatically adjusted...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div>
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="ic ic-2x ic-menu ib ib-size-xxxl"></span>
        <h6 class="above-heading">Customizable drop-down menu</h6>
        <h3>Mega Menu</h3>
        <p>Two styles: wide mega menu or classic drop-down menu. You can add any custom content to any category in the catalog...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div>
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="ic ic-2x ic-menu ib ib-size-xxxl"></span>
        <h6 class="above-heading">Customizable drop-down menu</h6>
        <h3>Mega Menu</h3>
        <p>Two styles: wide mega menu or classic drop-down menu. You can add any custom content to any category in the catalog...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div>
<div class="clearer"></div>-->


<div class="grid12-3 div-icons-content-top">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="title-icons-content-top">VENTA AL POR MAYOR</span>
        <img src="<?php echo $this->getSkinUrl('images/home/camiseta.png') ?>" alt="T-shirt" />
    </div>

</div>
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="title-icons-content-top">NUESTRAS FRANQUICIAS</span>
        <img src="<?php echo $this->getSkinUrl('images/home/casa.png') ?>" alt="T-shirt" />
    </div>

</div>
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="title-icons-content-top">NUESTROS CORNERS</span>
        <img src="<?php echo $this->getSkinUrl('images/home/corner.png') ?>" alt="T-shirt" />
    </div>

</div>
<div class="grid12-3">

    <div class="feature feature-icon-hover indent indent-size-xxxl">
        <span class="title-icons-content-top">MUESTRARIO EXPRÉS</span>
        <img src="<?php echo $this->getSkinUrl('images/home/cohete.png') ?>" alt="T-shirt" />
    </div>

</div>
<div class="clearer"></div>