<?php
class IMEI_Mymodule_Block_Adminhtml_Mymodule_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    //Creo la tabla
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setId('mymoduleGrid');
        $this->setDefaultSort('id');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getModel('mymodule/imei')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }

    public function _prepareColumns()
    {
        $this->addColumn('id', array(
            'header' => 'ID',
            'align' => 'right',
            'width' => '50px',
            'index' => 'id'
        ));

        $this->addColumn('imei_code', array(
           'header' => 'IMEI',
            'align' => 'left',
            'index' => 'imei_code'
        ));

        $this->addColumn('created', array(
            'header' => 'FECHA',
            'align' => 'left',
            'index' => 'created'
        ));

        $this->addColumn('estado', array(
            'header' => 'ESTADO',
            'align' => 'left',
            'index' => 'estado'
        ));

        $this->addColumn('customer', array(
            'header' => 'CUSTOMER',
            'align' => 'left',
            'index' => 'customer'
        ));

        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array('id' => $row->getId()));
    }
}





































































